---
apiVersion: v2
name: traefik
description: An Umbrella helm chart for traefik
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: traefik
    version: 37.3.0
    repository: https://traefik.github.io/charts
