---
traefik:
  entryPoints:
    web:
      address: :80
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      address: :443
      tls: {}
  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: [web, websecure]
      matchRule: Host(`traefik.cluster.simonjung.io`)
      tls:
        secretName: traefik-ingress-secret
certificate:
  secretName: traefik-ingress-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
