---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: traefik-ingress-certificate
spec:
    secretName: {{.Values.certificate.secretName}}
    issuerRef:
        name: {{.Values.certificate.issuerRef.name}}
        kind: {{.Values.certificate.issuerRef.kind}}
    dnsNames:
        - traefik.cluster.simonjung.io
