---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: traefik-ingress-certificate
spec:
    secretName: traefik-ingress-secret
    issuerRef:
        name: cloudflare-clusterissuer
        kind: ClusterIssuer
    dnsNames:
        - traefik.cluster.simonjung.io
